### PR TITLE
Decaffeinate

### PR DESCRIPTION
**Pull request by aminya**
This pull requests updates fs-plus **without changing the API**:
- decaffeinate: src code is converted to Modern JavaScript 
- Rollup: fs-plus is built with rollup which makes it load much faster
- babel: uses babel for conversion to cjs
- Enhances the performance and loading time

### Verification Process

Tests are untouched to show backward compatibility! As you see all of them pass.

### Release Notes

- decaffeinate: src code is converted to Modern JavaScript 
- Rollup: fs-plus is built with rollup which makes it load much faster
- babel: uses babel for conversion to cjs
- Enhances the performance and loading time

### CODE REVIEW

**Comment by aminya** [comment]
@sadick254 This is ready now

**Comment by aminya** [comment]
@sadick254 @darangi Could you take a look at this? I have some plans in my mind to improv fs-plus, which depend on this.

**Comment by sadick254** [comment]
@aminya Could you investigate what is causing the `node 14` failure on `appveyor`

**Comment by aminya** [comment]
@sadick254 That is just a one-time thing that happens in Appveyor sometimes. Restart the failing jobs and it will go away.

If you check it does not even start
image

**Comment by aminya** [comment]
@sadick254 Are you planning to merge this? 

I have big plans for fs-plus. I want to reexprt the missing methods from `fs-extra`, so we can just use `fs-plus` everywhere.

**Comment by sadick254** [comment]
Hey @aminya,
We are still very much open to decaffeination. This PR will be merged.
> Just as a reference, Atom maintainers were more open to decaffeination, but this seems to have changed for unknown reasons. For example, see this PR which was merged in a day atom/event-kit#38

Right now we are quite a small team with a lot to do. We might not be able to merge PR's in a day.

**Comment by sadick254** [comment]
@aminya When decaffeinating please avoid introducing other changes. You should create separate PR's for the changes unrelated to decaffeination.

**Comment by aminya** [comment]
I did not do that. I have actually kept my changes for future PRs.

These changes are my manual work to make decaffeination more appealing. When you use the decaffeinate tool, it generates some suggestions. I just applied those so the code looks succinct. These recommendations are usually these:

- Remove implicit returns: remove unnecessary return in functions because of CoffeeScript
- Remove inline assignment: move assignment out of if the head
- Shorter null check: using `if (variable)` instead of `if (variable != null)` whenever it is safe
- Remove IIFE: unnecessary returns because of CoffeeScript
- Remove unnecessary Array.from
- Remove guard: using if checks instead of optional chaining in CoffeeScript (generated if not using optional chaining). Instead, we use a new babel version with optional chaining enabled. 
...

**Comment by sadick254** [comment]
I am ok with the suggestions. In this PR i see the introduction to rollup. This could have been a separate PR. Just wanted to bring it to your attention.

**Comment by aminya** [comment]
I can move it to another PR if it helps. That is not a problem at all. We can use babel by itself too.

**Comment by sadick254** [comment]
No need. I have already reviewed the changes and happy to merge it as it is.

**Comment by aminya** [comment]
Awesome! Thanks for merging.

**Pull request merged**
